# https://docs.travis-ci.com/user/languages/python

language: python

python:
    - "3.6"      # current default Python on Travis CI
    - "3.7"
    - "3.8"
  
install:
    - pip install -r ci-requirements.txt

script:
    - python -m pytest --cov=./
    - black --check --verbose .
    - flake8 --verbose
    - bandit --configfile bandit.yml --recursive .
    - mypy --config-file=mypy.ini dataworks/

after_script:
    - codecov --token=$CODECOV_TOKEN
    - pdoc --html -c show_type_annotations=True dataworks --output-dir public/

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: true
    on:
      branch: master
      python: "3.8"
